run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.25'

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - usetesting
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 150

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  mnd:
    ignored-numbers:
      - '0'
      - '1'
      - '2'
    ignored-functions:
      - 'strconv.Parse*'

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    excludes:
      - G104 # Audit errors not checked
    config:
      G306: "0644"

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  nestif:
    min-complexity: 4

  stylecheck:
    checks:
      - all
      - '-ST1000' # Package comments
      - '-ST1003' # Underscores in names

issues:
  exclude-rules:
    # Exclude dupl from test files (test cases often have similar structure)
    - path: _test\.go
      linters:
        - dupl

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - errcheck
      severity: error
