version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.25'

output:
  formats:
    text:
      path: stdout
  sort-results: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  disable:
    - depguard
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - usetesting
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - dupl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    dupl:
      threshold: 150

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    mnd:
      ignored-numbers:
        - '0'
        - '1'
        - '2'
      ignored-functions:
        - 'strconv.Parse*'

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code

    gosec:
      excludes:
        - G104
      config:
        G306: "0644"

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy

    nestif:
      min-complexity: 4

    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1003'

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

severity:
  default: warning
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - errcheck
      severity: error
